---
- name: 
  hosts: all
  become: true
  vars:
    docker_users:
      - vagrant

  tasks:
  - name: Install packages
    package:
      name:
        - pip
        - conntrack
      state: present
     
  - name: Install kubernetes python package
    pip:
      name: 
      - kubernetes==23.3.0

  - name: Check the minikube status
    command: minikube status
    register: minikube_status
    changed_when: false
    ignore_errors: true

  - name: Start minikube.
    command: minikube start --force 
    when: "not minikube_status.stdout or 'Running' not in minikube_status.stdout"
    
  - name: Add an apt signing key for Kubernetes
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Ensure /etc/apt/keyrings directory exists
    file:
      path: /etc/apt/keyrings
      state: directory
      mode: '0755'
  
  - name: Download Kubernetes repository GPG key
    get_url:
      url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
      dest: /tmp/kubernetes-release.key

  - name: Add the GPG key for the Kubernetes repository
    shell: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-release.key
    args:
      executable: /bin/bash
    
  - name: Adding apt repository for Kubernetes
    apt_repository:
      repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /
      state: present
      filename: kubernetes.list

  - name: Install packages
    package:
      name:
        - socat
        - kubectl
      state: present
  
  - name: Download Helm command line tool
    uri:
      url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      return_content: true
    register: helm_installer

  - name: Install Helm
    command:
      cmd: bash
      stdin: "{{ helm_installer.content }}"
      creates: /usr/local/bin/helm

  roles:
    - geerlingguy.docker
    - gantsign.minikube

  collections:
    - kubernetes.core
